--Add primary key to authors table

ALTER TABLE authors
ADD CONSTRAINT authors_pk PRIMARY KEY (id);

--Books table

create TABLE books (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   author_id BIGINT NOT NULL,
   title VARCHAR(255) NOT NULL,
   year INTEGER NOT NULL CHECK (year >= 1 AND year <= 2024),
   create_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
   update_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
   FOREIGN KEY (author_id) REFERENCES authors(id)
);