--Add primary key to books table

ALTER TABLE books
ADD CONSTRAINT books_pk PRIMARY KEY (id);

--Books table

create TABLE book_ratings (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   book_id BIGINT NOT NULL,
   rating INTEGER CHECK (rating >= 1 AND rating <= 5),
   create_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
   update_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
   FOREIGN KEY (book_id) REFERENCES books(id)
);